# Generated by Django 5.2.5 on 2025-08-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
