# Generated by Django 5.1.6 on 2025-08-02 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_products_shoep"),
        ("manager", "0002_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="shop",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.shop",
            ),
            preserve_default=False,
        ),
    ]
