# Generated by Django 5.1.6 on 2026-09-13 19:22

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_cart_delivery_inventory_payment_productvariant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adress",
            name="phone_num",
            field=models.CharField(
                blank=True,
                default="",
                max_length=13,
                validators=[api.validators.ethiopian_phone_validator],
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("popular_picks", "Popular Picks"),
                    ("bags", "Bags"),
                    ("clothes", "Clothes"),
                    ("shoes", "Shoes"),
                ],
                default="clothes",
                max_length=50,
                null=True,
            ),
        ),
    ]
