# Generated by Django 5.1.6 on 2025-08-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_cartitem_product_alter_orderitem_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.CharField(
                choices=[
                    ("popular_picks", "Popular Picks"),
                    ("bag", "Bag"),
                    ("clothe", "Clothe"),
                    ("shoes", "Shoes"),
                ],
                default="popular_picks",
                max_length=50,
            ),
        ),
    ]
