# Generated by Django 5.1.6 on 2025-08-06 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_products_category"),
        ("manager", "0004_shop_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop",
                to="manager.shop",
            ),
        ),
    ]
