# Generated by Django 5.1.6 on 2025-08-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_order_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_process", "In_process"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("popular_picks", "Popular Picks"),
                    ("bag", "Bag"),
                    ("clothe", "Clothe"),
                    ("shoes", "Shoes"),
                ],
                default="popular_picks",
                max_length=50,
                null=True,
            ),
        ),
    ]
