# Generated by Django 5.1.6 on 2025-08-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_adress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
    ]
