# Generated by Django 5.1.6 on 2025-08-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="adress",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adress",
            name="phone_num",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
