# Generated by Django 5.2.5 on 2025-08-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('bags', 'Bags'), ('clothes', 'Clothes'), ('shoes', 'Shoes')], default='clothes', max_length=50, null=True),
        ),
    ]
