# Generated by Django 5.1.6 on 2025-08-20 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_adress_is_default_adress_phone_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="api.adress"
            ),
        ),
    ]
