# Generated by Django 5.1.6 on 2025-08-20 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_order_shipping_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.OneToOneField(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="api.adress"
            ),
        ),
    ]
