# Generated by Django 5.2.5 on 2025-08-17 14:25

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_products_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adress',
            name='phone_num',
            field=models.CharField(default='', max_length=13, validators=[api.validators.ethiopian_phone_validator]),
            preserve_default=False,
        ),
    ]
