# Generated by Django 5.2.5 on 2025-08-20 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_fcmtoken'),
        ('manager', '0006_rename_admin_shopowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtoken',
            name='shop',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='manager.shop'),
            preserve_default=False,
        ),
    ]
