# Generated by Django 5.2.5 on 2025-08-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_order_shipping_address'),
        ('api', '0023_fcmtoken_shop'),
    ]

    operations = [
    ]
