# Generated by Django 5.2.5 on 2025-08-21 08:50

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20250821_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='adress',
            name='phone_num',
            field=models.CharField(max_length=13, validators=[api.validators.ethiopian_phone_validator]),
        ),
    ]
