# Generated by Django 5.2.5 on 2025-08-21 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.adress'),
        ),
    ]
