# Generated by Django 5.1.6 on 2026-09-13 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0002_user_first_name_user_is_verified_user_last_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(blank=True, default="", max_length=80)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("last_update_id", models.BigIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_state",
                        to="user.telegramaccount",
                    ),
                ),
            ],
        ),
    ]
