# Generated by Django 5.2.5 on 2025-08-22 14:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_profile', max_length=255, null=True, verbose_name='profile_photo'),
        ),
    ]
