# Generated by Django 5.1.6 on 2025-08-03 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_shop_description"),
        ("user", "0002_remove_user_shope_user_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.shop",
            ),
        ),
    ]
