# Generated by Django 5.1.6 on 2025-08-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
