# Generated by Django 5.1.6 on 2025-08-02 20:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "shope_id",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=100, unique=True
                    ),
                ),
            ],
        ),
    ]
