# Generated by Django 5.1.6 on 2025-08-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_products_shop"),
        ("manager", "0002_shop"),
        ("user", "0002_remove_user_shope_user_shop"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Shope",
        ),
    ]
