# Generated by Django 5.1.6 on 2026-09-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="is_marketplace",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shop",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
