# Generated by Django 5.1.6 on 2025-08-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_delete_shope"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="description",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
