# Generated by Django 5.1.6 on 2025-08-07 20:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_admin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Admin",
            new_name="ShopOwner",
        ),
    ]
